### ISSUE TITLE
errors when npm installing the seed project

### ISSUE THREAD

**Issue by hariseldon78** [pana-cc/mocha-typescript#101] opened 2018-07-18 23:51 UTC
i just git cloned the seed project linked in the readme, and these are the errors I got. I also have the same errors on another project, and i'm pretty sure it worked before and at some point it got broken with some upgrade, but i'm having a hard time finding which upgrade exactly...

tsc --version
Version 2.8.3

node --version
v8.11.1

npm --version
6.2.0

```
npm install

> mocha-typescript-seed@1.0.0 prepare [...]/tmp/mocha-typescript-seed
> tsc

node_modules/@types/mocha/index.d.ts:2680:13 - error TS2300: Duplicate identifier 'beforeEach'.

2680 declare var beforeEach: Mocha.HookFunction;
                 ~~~~~~~~~~


node_modules/@types/mocha/index.d.ts:2698:13 - error TS2300: Duplicate identifier 'afterEach'.

2698 declare var afterEach: Mocha.HookFunction;
                 ~~~~~~~~~


node_modules/@types/mocha/index.d.ts:2714:13 - error TS2300: Duplicate identifier 'describe'.

2714 declare var describe: Mocha.SuiteFunction;
                 ~~~~~~~~


node_modules/@types/mocha/index.d.ts:2735:13 - error TS2300: Duplicate identifier 'xdescribe'.

2735 declare var xdescribe: Mocha.PendingSuiteFunction;
                 ~~~~~~~~~


node_modules/@types/mocha/index.d.ts:2749:13 - error TS2300: Duplicate identifier 'it'.

2749 declare var it: Mocha.TestFunction;
                 ~~


node_modules/@types/mocha/index.d.ts:2770:13 - error TS2300: Duplicate identifier 'xit'.

2770 declare var xit: Mocha.PendingTestFunction;
                 ~~~


../node_modules/@types/jasmine/index.d.ts:15:18 - error TS2300: Duplicate identifier 'describe'.

15 declare function describe(description: string, specDefinitions: () => void): void;
                    ~~~~~~~~


../node_modules/@types/jasmine/index.d.ts:17:18 - error TS2300: Duplicate identifier 'xdescribe'.

17 declare function xdescribe(description: string, specDefinitions: () => void): void;
                    ~~~~~~~~~


../node_modules/@types/jasmine/index.d.ts:26:18 - error TS2300: Duplicate identifier 'it'.

26 declare function it(expectation: string, assertion?: (done: DoneFn) => void, timeout?: number): void;
                    ~~


../node_modules/@types/jasmine/index.d.ts:36:18 - error TS2300: Duplicate identifier 'xit'.

36 declare function xit(expectation: string, assertion?: (done: DoneFn) => void, timeout?: number): void;
                    ~~~


../node_modules/@types/jasmine/index.d.ts:51:18 - error TS2300: Duplicate identifier 'beforeEach'.

51 declare function beforeEach(action: (done: DoneFn) => void, timeout?: number): void;
                    ~~~~~~~~~~


../node_modules/@types/jasmine/index.d.ts:58:18 - error TS2300: Duplicate identifier 'afterEach'.

58 declare function afterEach(action: (done: DoneFn) => void, timeout?: number): void;
                    ~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:39:15 - error TS2304: Cannot find name 'Event'.

39 type _Event = Event;
                 ~~~~~


../node_modules/@types/jquery/index.d.ts:43:41 - error TS2304: Cannot find name 'Node'.

43 interface JQueryStatic<TElement extends Node = HTMLElement> {
                                           ~~~~


../node_modules/@types/jquery/index.d.ts:43:48 - error TS2304: Cannot find name 'HTMLElement'.

43 interface JQueryStatic<TElement extends Node = HTMLElement> {
                                                  ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:93:55 - error TS2304: Cannot find name 'Node'.

93         step: JQuery.PlainObject<JQuery.AnimationHook<Node>>;
                                                         ~~~~


../node_modules/@types/jquery/index.d.ts:126:57 - error TS2304: Cannot find name 'Document'.

126     (html: JQuery.htmlString, ownerDocument_attributes: Document | JQuery.PlainObject): JQuery<TElement>;
                                                            ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:135:42 - error TS2304: Cannot find name 'Element'.

135     (selector: JQuery.Selector, context: Element | Document | JQuery | undefined): JQuery<TElement>;
                                             ~~~~~~~


../node_modules/@types/jquery/index.d.ts:135:52 - error TS2304: Cannot find name 'Document'.

135     (selector: JQuery.Selector, context: Element | Document | JQuery | undefined): JQuery<TElement>;
                                                       ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:138:23 - error TS2304: Cannot find name 'Node'.

138     <FElement extends Node = HTMLElement>(window: Window, discriminator: boolean): JQueryStatic<FElement>;
                          ~~~~


../node_modules/@types/jquery/index.d.ts:138:30 - error TS2304: Cannot find name 'HTMLElement'.

138     <FElement extends Node = HTMLElement>(window: Window, discriminator: boolean): JQueryStatic<FElement>;
                                 ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:154:90 - error TS2304: Cannot find name 'Element'.

154     (selector_object_callback?: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Element> | JQuery |
                                                                                             ~~~~~~~


../node_modules/@types/jquery/index.d.ts:156:17 - error TS2304: Cannot find name 'Document'.

156         ((this: Document, $: JQueryStatic<TElement>) => void)): JQuery<TElement>;
                    ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:234:25 - error TS2304: Cannot find name 'Element'.

234     contains(container: Element, contained: Element): boolean;
                            ~~~~~~~


../node_modules/@types/jquery/index.d.ts:234:45 - error TS2304: Cannot find name 'Element'.

234     contains(container: Element, contained: Element): boolean;
                                                ~~~~~~~


../node_modules/@types/jquery/index.d.ts:235:15 - error TS2304: Cannot find name 'Element'.

235     css(elem: Element, unknown: any): any;
                  ~~~~~~~


../node_modules/@types/jquery/index.d.ts:245:19 - error TS2304: Cannot find name 'Element'.

245     data(element: Element, key: string, undefined: undefined): any; // tslint:disable-line:unified-signatures
                      ~~~~~~~


../node_modules/@types/jquery/index.d.ts:255:22 - error TS2304: Cannot find name 'Element'.

255     data<T>(element: Element, key: string, value: T): T;
                         ~~~~~~~


../node_modules/@types/jquery/index.d.ts:266:19 - error TS2304: Cannot find name 'Element'.

266     data(element: Element, key?: string): any;
                      ~~~~~~~


../node_modules/@types/jquery/index.d.ts:275:22 - error TS2304: Cannot find name 'Element'.

275     dequeue(element: Element, queueName?: string): void;
                         ~~~~~~~


../node_modules/@types/jquery/index.d.ts:556:22 - error TS2304: Cannot find name 'Element'.

556     hasData(element: Element): boolean;
                         ~~~~~~~


../node_modules/@types/jquery/index.d.ts:643:20 - error TS2304: Cannot find name 'Node'.

643     isXMLDoc(node: Node): boolean;
                       ~~~~


../node_modules/@types/jquery/index.d.ts:728:38 - error TS2304: Cannot find name 'Document'.

728     parseHTML(data: string, context: Document | null | undefined, keepScripts: boolean): JQuery.Node[];
                                         ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:738:51 - error TS2304: Cannot find name 'Document'.

738     parseHTML(data: string, context_keepScripts?: Document | null | boolean): JQuery.Node[];
                                                      ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:755:29 - error TS2304: Cannot find name 'XMLDocument'.

755     parseXML(data: string): XMLDocument;
                                ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:2948:21 - error TS2304: Cannot find name 'Element'.

2948     queue<T extends Element>(element: T, queueName?: string, newQueue?: JQuery.TypeOrArray<JQuery.QueueFunction<T>>): JQuery.Queue<T>;
                         ~~~~~~~


../node_modules/@types/jquery/index.d.ts:2965:25 - error TS2304: Cannot find name 'Element'.

2965     removeData(element: Element, name?: string): void;
                             ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3024:22 - error TS2304: Cannot find name 'Element'.

3024     unique<T extends Element>(array: T[]): T[];
                          ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3034:26 - error TS2304: Cannot find name 'Element'.

3034     uniqueSort<T extends Element>(array: T[]): T[];
                              ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3101:35 - error TS2304: Cannot find name 'Node'.

3101 interface JQuery<TElement extends Node = HTMLElement> extends Iterable<TElement> {
                                       ~~~~


../node_modules/@types/jquery/index.d.ts:3101:42 - error TS2304: Cannot find name 'HTMLElement'.

3101 interface JQuery<TElement extends Node = HTMLElement> extends Iterable<TElement> {
                                              ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3125:45 - error TS2304: Cannot find name 'Element'.

3125     add(selector: JQuery.Selector, context: Element): this;
                                                 ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3137:56 - error TS2304: Cannot find name 'Element'.

3137     add(selector: JQuery.Selector | JQuery.TypeOrArray<Element> | JQuery.htmlString | JQuery): this;
                                                            ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3188:34 - error TS2304: Cannot find name 'Document'.

3188     ajaxComplete(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxOptions: JQuery.AjaxSettings) => void | false): this;
                                      ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3188:64 - error TS2304: Cannot find name 'Document'.

3188     ajaxComplete(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxOptions: JQuery.AjaxSettings) => void | false): this;
                                                                    ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3196:31 - error TS2304: Cannot find name 'Document'.

3196     ajaxError(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxSettings: JQuery.AjaxSettings, thrownError: string) => void | false): this;
                                   ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3196:61 - error TS2304: Cannot find name 'Document'.

3196     ajaxError(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxSettings: JQuery.AjaxSettings, thrownError: string) => void | false): this;
                                                                 ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3204:30 - error TS2304: Cannot find name 'Document'.

3204     ajaxSend(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxOptions: JQuery.AjaxSettings) => void | false): this;
                                  ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3204:60 - error TS2304: Cannot find name 'Document'.

3204     ajaxSend(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxOptions: JQuery.AjaxSettings) => void | false): this;
                                                                ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3212:31 - error TS2304: Cannot find name 'Document'.

3212     ajaxStart(handler: (this: Document) => void | false): this;
                                   ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3220:30 - error TS2304: Cannot find name 'Document'.

3220     ajaxStop(handler: (this: Document) => void | false): this;
                                  ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3228:33 - error TS2304: Cannot find name 'Document'.

3228     ajaxSuccess(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxOptions: JQuery.AjaxSettings, data: JQuery.PlainObject) => void | false): this;
                                     ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3228:63 - error TS2304: Cannot find name 'Document'.

3228     ajaxSuccess(handler: (this: Document, event: JQuery.Event<Document>, jqXHR: JQuery.jqXHR, ajaxOptions: JQuery.AjaxSettings, data: JQuery.PlainObject) => void | false): this;
                                                                   ~~~~~~~~


../node_modules/@types/jquery/index.d.ts:3304:79 - error TS2304: Cannot find name 'Element'.

3304     appendTo(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Element> | JQuery): this;
                                                                                   ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3491:49 - error TS2304: Cannot find name 'Element'.

3491     closest(selector: JQuery.Selector, context: Element): this;
                                                     ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3503:41 - error TS2304: Cannot find name 'Element'.

3503     closest(selector: JQuery.Selector | Element | JQuery): this;
                                             ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3510:35 - error TS2304: Cannot find name 'Text'.

3510     contents(): JQuery<TElement | Text | Comment>;
                                       ~~~~


../node_modules/@types/jquery/index.d.ts:3510:42 - error TS2304: Cannot find name 'Comment'.

3510     contents(): JQuery<TElement | Text | Comment>;
                                              ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3873:59 - error TS2304: Cannot find name 'Element'.

3873     filter(selector: JQuery.Selector | JQuery.TypeOrArray<Element> | JQuery | ((this: TElement, index: number, element: TElement) => boolean)): this;
                                                               ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3884:38 - error TS2304: Cannot find name 'Element'.

3884     find(selector: JQuery.Selector | Element | JQuery): this;
                                          ~~~~~~~


../node_modules/@types/jquery/index.d.ts:3984:28 - error TS2304: Cannot find name 'Element'.

3984     has(selector: string | Element): this;
                                ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4084:39 - error TS2304: Cannot find name 'Element'.

4084     index(element?: JQuery.Selector | Element | JQuery): number;
                                           ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4133:82 - error TS2304: Cannot find name 'Element'.

4133     insertAfter(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Element> | JQuery): this;
                                                                                      ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4142:83 - error TS2304: Cannot find name 'Element'.

4142     insertBefore(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Element> | JQuery): this;
                                                                                       ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4157:55 - error TS2304: Cannot find name 'Element'.

4157     is(selector: JQuery.Selector | JQuery.TypeOrArray<Element> | JQuery | ((this: TElement, index: number, element: TElement) => boolean)): boolean;
                                                           ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4425:44 - error TS2304: Cannot find name 'Element'.

4425     nextUntil(selector?: JQuery.Selector | Element | JQuery, filter?: JQuery.Selector): this;
                                                ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4438:56 - error TS2304: Cannot find name 'Element'.

4438     not(selector: JQuery.Selector | JQuery.TypeOrArray<Element> | JQuery | ((this: TElement, index: number, element: TElement) => boolean)): this;
                                                            ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4766:47 - error TS2304: Cannot find name 'Element'.

4766     parentsUntil(selector?: JQuery.Selector | Element | JQuery, filter?: JQuery.Selector): this;
                                                   ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4802:80 - error TS2304: Cannot find name 'Element'.

4802     prependTo(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Element> | JQuery): this;
                                                                                    ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4831:44 - error TS2304: Cannot find name 'Element'.

4831     prevUntil(selector?: JQuery.Selector | Element | JQuery, filter?: JQuery.Selector): this;
                                                ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4904:35 - error TS2304: Cannot find name 'Element'.

4904     pushStack(elements: ArrayLike<Element>, name: string, args: any[]): this;
                                       ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4912:35 - error TS2304: Cannot find name 'Element'.

4912     pushStack(elements: ArrayLike<Element>): this;
                                       ~~~~~~~


../node_modules/@types/jquery/index.d.ts:4939:45 - error TS2304: Cannot find name 'Node'.

4939     queue(queueName?: string): JQuery.Queue<Node>;
                                                 ~~~~


../node_modules/@types/jquery/index.d.ts:5003:70 - error TS2304: Cannot find name 'Element'.

5003     replaceAll(target: JQuery.Selector | JQuery | JQuery.TypeOrArray<Element>): this;
                                                                          ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5014:77 - error TS2304: Cannot find name 'Element'.

5014     replaceWith(newContent: JQuery.htmlString | JQuery | JQuery.TypeOrArray<Element> | ((this: TElement) => any)): this;
                                                                                 ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5532:65 - error TS2304: Cannot find name 'Element'.

5532     wrap(wrappingElement: JQuery.Selector | JQuery.htmlString | Element | JQuery | ((this: TElement, index: number) => string | JQuery)): this;
                                                                     ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5545:68 - error TS2304: Cannot find name 'Element'.

5545     wrapAll(wrappingElement: JQuery.Selector | JQuery.htmlString | Element | JQuery | ((this: TElement) => string | JQuery)): this;
                                                                        ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5558:70 - error TS2304: Cannot find name 'Element'.

5558     wrapInner(wrappingElement: JQuery.Selector | JQuery.htmlString | Element | JQuery | ((this: TElement, index: number) => string | JQuery | Element)): this;
                                                                          ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5558:143 - error TS2304: Cannot find name 'Element'.

5558     wrapInner(wrappingElement: JQuery.Selector | JQuery.htmlString | Element | JQuery | ((this: TElement, index: number) => string | JQuery | Element)): this;
                                                                                                                                                   ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5568:17 - error TS2304: Cannot find name 'Element'.

5568     type Node = Element | Text | Comment;
                     ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5568:27 - error TS2304: Cannot find name 'Text'.

5568     type Node = Element | Text | Comment;
                               ~~~~


../node_modules/@types/jquery/index.d.ts:5568:34 - error TS2304: Cannot find name 'Comment'.

5568     type Node = Element | Text | Comment;
                                      ~~~~~~~


../node_modules/@types/jquery/index.d.ts:5887:21 - error TS2304: Cannot find name 'XMLHttpRequest'.

5887             xhr?(): XMLHttpRequest;
                         ~~~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:6316:50 - error TS2304: Cannot find name 'XMLHttpRequest'.

6316         interface XHRFields extends Partial<Pick<XMLHttpRequest, 'onreadystatechange' | 'responseType' | 'timeout' | 'withCredentials' | 'msCaching'>> { }
                                                      ~~~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:6336:14 - error TS2304: Cannot find name 'XMLHttpRequest'.

6336         Pick<XMLHttpRequest, 'abort' | 'getAllResponseHeaders' | 'getResponseHeader' | 'overrideMimeType' | 'readyState' | 'responseText' |
                  ~~~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:6338:22 - error TS2304: Cannot find name 'XMLHttpRequest'.

6338         Partial<Pick<XMLHttpRequest, 'responseXML'>> {
                          ~~~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7716:37 - error TS2304: Cannot find name 'EventTarget'.

7716     interface EventStatic<TTarget = EventTarget> {
                                         ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7826:31 - error TS2304: Cannot find name 'EventTarget'.

7826     interface Event<TTarget = EventTarget,
                                   ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7827:44 - error TS2304: Cannot find name 'PointerEvent'.

7827         TData = null> extends Partial<Pick<PointerEvent & KeyboardEvent & TouchEvent, 'altKey' | 'bubbles' | 'cancelable' |
                                                ~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7827:59 - error TS2304: Cannot find name 'KeyboardEvent'.

7827         TData = null> extends Partial<Pick<PointerEvent & KeyboardEvent & TouchEvent, 'altKey' | 'bubbles' | 'cancelable' |
                                                               ~~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7827:75 - error TS2304: Cannot find name 'TouchEvent'.

7827         TData = null> extends Partial<Pick<PointerEvent & KeyboardEvent & TouchEvent, 'altKey' | 'bubbles' | 'cancelable' |
                                                                               ~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7875:51 - error TS2304: Cannot find name 'EventTarget'.

7875     interface EventHandler<TCurrentTarget extends EventTarget, TData = null> extends EventHandlerBase<TCurrentTarget, JQuery.Event<TCurrentTarget, TData>> { }
                                                       ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:7875:103 - error TS2344: Type 'TCurrentTarget' does not satisfy the constraint 'object'.

7875     interface EventHandler<TCurrentTarget extends EventTarget, TData = null> extends EventHandlerBase<TCurrentTarget, JQuery.Event<TCurrentTarget, TData>> { }
                                                                                                           ~~~~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:8029:55 - error TS2304: Cannot find name 'EventTarget'.

8029 interface JQueryEventConstructor extends JQuery.Event<EventTarget> { }
                                                           ~~~~~~~~~~~


../node_modules/@types/jquery/index.d.ts:8032:64 - error TS2304: Cannot find name 'Element'.

8032 interface JQueryAnimationOptions extends JQuery.EffectsOptions<Element> { }
                                                                    ~~~~~~~


../node_modules/@types/jquery/index.d.ts:8067:41 - error TS2304: Cannot find name 'Event'.

8067 interface BaseJQueryEventObject extends Event {
                                             ~~~~~


../node_modules/@types/jquery/index.d.ts:8072:20 - error TS2304: Cannot find name 'Element'.

8072     currentTarget: Element;
                        ~~~~~~~


../node_modules/@types/jquery/index.d.ts:8082:21 - error TS2304: Cannot find name 'Element'.

8082     delegateTarget: Element;
                         ~~~~~~~


../node_modules/@types/jquery/index.d.ts:8107:20 - error TS2304: Cannot find name 'Event'.

8107     originalEvent: Event;
                        ~~~~~


../node_modules/@types/jquery/index.d.ts:8117:20 - error TS2304: Cannot find name 'Element'.

8117     relatedTarget: Element;
                        ~~~~~~~


../node_modules/@types/jquery/index.d.ts:8137:13 - error TS2304: Cannot find name 'Element'.

8137     target: Element;
                 ~~~~~~~


../node_modules/@types/lodash/index.d.ts:10186:53 - error TS2344: Type 'T' does not satisfy the constraint 'object'.

10186         isWeakSet<T>(value?: any): value is WeakSet<T>;
                                                          ~


../node_modules/@types/webpack/index.d.ts:590:28 - error TS2507: Type 'typeof import("/[...]tmp/node_modules/@types/tapable/index")' is not a constructor function type.

590     class Compiler extends Tapable implements ICompiler {
                               ~~~~~~~


../node_modules/@types/webpack/index.d.ts:632:46 - error TS2694: Namespace '"/[...]/tmp/node_modules/@types/tapable/index"' has no exported member 'Plugin'.

632     abstract class Plugin implements Tapable.Plugin {
                                                 ~~~~~~


../node_modules/@types/webpack/index.d.ts:636:53 - error TS2694: Namespace '"/[...]tmp/node_modules/@types/tapable/index"' has no exported member 'Plugin'.

636     abstract class ResolvePlugin implements Tapable.Plugin {
                                                        ~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mocha-typescript-seed@1.0.0 prepare: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mocha-typescript-seed@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /[...]/.npm/_logs/2018-07-18T23_41_06_608Z-debug.log
```

**Comment by silkentrance** [comment] 2018-07-19 15:45
I just ran the same and it did work just fine:

```
$ git clone https://github.com/pana-cc/mocha-typescript-seed.git
Cloning into 'mocha-typescript-seed'...
remote: Counting objects: 39, done.
remote: Total 39 (delta 0), reused 0 (delta 0), pack-reused 39
Unpacking objects: 100% (39/39), done.
$ cd mocha-typescript-seed/
$ ls
LICENSE		README.md	package.json	src		test		tsconfig.json
$ npm install

> mocha-typescript-seed@1.0.0 prepare /Volumes/workspaces/01-coldrye/01-collaboration/mocha-typescript-seed
> tsc

npm notice created a lockfile as package-lock.json. You should commit this file.
added 385 packages from 617 contributors in 88.953s
$ npm test

> mocha-typescript-seed@1.0.0 pretest /Volumes/workspaces/01-coldrye/01-collaboration/mocha-typescript-seed
> tsc


> mocha-typescript-seed@1.0.0 test /Volumes/workspaces/01-coldrye/01-collaboration/mocha-typescript-seed
> nyc mocha



start server
server started
  vanilla bdd
  vanilla bdd test
    ✓ test

  vanilla tdd
  vanilla tdd test
    ✓ test

  UnitTest
  UnitTest big is true with big number
    ✓ big is true with big number
  UnitTest big is false with small number
    ✓ big is false with small number

  nested class suite
    NestedTest
  nested class suite NestedTest a test
      ✓ a test

kill server
server killed

  5 passing (2s)


=============================== Coverage summary ===============================
Statements   : 100% ( 4/4 )
Branches     : 100% ( 2/2 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 4/4 )
================================================================================
```

**Comment by silkentrance** [comment] 2018-07-19 15:50
Can you please post the devDependencies/dependencies part of your package.json?

**Comment by hariseldon78** [comment] 2018-07-19 22:45
it's the same of the github repo, unchanged. Clearly there is something external that influence the result, maybe some package that I installed globally?

`{
  "name": "mocha-typescript-seed",
  "version": "1.0.0",
  "description": "A project with mocha-typescript enabled",
  "main": "index.js",
  "scripts": {
    "pretest": "tsc",
    "test": "nyc mocha",
    "watch": "mocha-typescript-watch",
    "prepare": "tsc"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/pana-cc/mocha-typescript-seed.git"
  },
  "author": "",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/pana-cc/mocha-typescript-seed/issues"
  },
  "homepage": "https://github.com/pana-cc/mocha-typescript-seed#readme",
  "devDependencies": {
    "@types/chai": "*",
    "@types/mocha": "*",
    "chai": "*",
    "mocha": "*",
    "mocha-typescript": "*",
    "nyc": "*",
    "source-map-support": "*",
    "ts-node": "^3.3.0",
    "typescript": "*"
  },
  "nyc": {
    "check-coverage": true,
    "lines": 80,
    "statements": 80,
    "functions": 80,
    "branches": 80,
    "include": [
      "src/**/*.js"
    ],
    "exclude": [
      "test/**/*.js"
    ],
    "reporter": [
      "lcov",
      "text-summary"
    ],
    "all": true
  }
}
`

**Comment by silkentrance** [comment] 2018-07-20 20:21
@hariseldon78 I was asking, because in your error log it reads


```
../node_modules/@types/jquery/index.d.ts:8032:64 - error TS2304: Cannot find name 'Element'.

../node_modules/@types/webpack/index.d.ts:636:53 - error TS2694: Namespace '"/[...]tmp/node_modules/@types/tapable/index"' has no exported member 'Plugin'.

636     abstract class ResolvePlugin implements Tapable.Plugin {
                                                        ~~~~~~
```

which points to both a jquery and webpack dependency.

Something of which is not a part of the seed package.

**Comment by silkentrance** [comment] 2018-07-20 21:45
Closing since this is definitely not caused by us and the user is failing to provide us with more information.

**Closed by silkentrance** 2018-07-20 21:45 UTC

**Comment by hariseldon78** [comment] 2018-07-21 17:08
ok I found the source of the problem: there was a node_modules folder in the parent folder of the project, and for some reason npm decided to merge the two node_modules folder... removing the folder solved the problem

**Comment by robolivable** [comment] 2020-09-29 21:47
I faced a similar issue @hariseldon78 except in my case there was a user defined on my machine with the name node_modules..... I can't begin to describe how that user got there in the first place, but regardless it seems like the compiler likes to grab any node_modules folder it finds in parent directories (even if it's parallel to your current parent directory?!)...
