### ISSUE TITLE
BDD DSL is not well documented

### ISSUE THREAD

**Issue by Justus-Maier** [pana-cc/mocha-typescript#40] opened 2017-08-04 09:49 UTC
The readme states:
> The test interface provides support for mocha's built-in tdd, bdd: describe/suite, it/test, timeout, slow, it.only and it.skip; as well as TypeScript decorators based test UI for classes. You can mix and match

I tried `@describe/@it` without success. Please add example tests!
Sorry for hijacking #23

**Comment by Justus-Maier** [comment] 2017-08-04 10:00
Well I get now. Here is an idea for an example test:
```ts
import { suite, test, slow, timeout } from "mocha-typescript";

describe('mocha-typescript mix&match', () => {
  it('should work', () => {
    return new Promise((f, r) => f());
  });
  @suite(timeout(1000))
  class foo {
    @test()
    bar() {
      return new Promise((f, r) => setTimeout(f, 1001));
    }
  }
});
```

**Comment by pana-cc** [comment] 2017-09-13 10:18
:+1: This is actually a duplicate of https://github.com/pana-cc/mocha-typescript/issues/3 but I guess it would be better to address it in the docs.

**Comment by pana-cc** [comment] 2017-09-13 10:24
I've updated the readme.

**Closed by pana-cc** 2017-09-13 10:24 UTC
Labels: enhancement
