### ISSUE TITLE
Missing Mocha.* types - install @types/mocha

### ISSUE THREAD

**Issue by PanayotCankov** [pana-cc/mocha-typescript#26] opened 2017-04-27 06:45 UTC
It turns out this is a breaking change moving from `1.0.*` to `1.1.*`. The mocha-typescript typings now use Mocha's types from `@types/mocha`. To workaround this `npm i @types/mocha --save-dev` should do. This need a proper patch, since in pre `1.1.*` the `@types/mocha` were not required to be added as dependency for mocha-typescript to work, this may break some of you.
I am sorry.

``` bash
node_modules/mocha-typescript/index.d.ts(9,30): error TS2304: Cannot find name 'MochaDone'.
node_modules/mocha-typescript/index.d.ts(10,29): error TS2304: Cannot find name 'MochaDone'.
node_modules/mocha-typescript/index.d.ts(12,26): error TS2304: Cannot find name 'MochaDone'.
node_modules/mocha-typescript/index.d.ts(13,25): error TS2304: Cannot find name 'MochaDone'.
node_modules/mocha-typescript/index.d.ts(14,9): error TS7013: Construct signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/mocha-typescript/index.d.ts(17,22): error TS2694: Namespace 'Mocha' has no exported member 'ISuiteCallbackContext'.
node_modules/mocha-typescript/index.d.ts(17,56): error TS2694: Namespace 'Mocha' has no exported member 'ISuiteCallbackContext'.
node_modules/mocha-typescript/index.d.ts(20,22): error TS2694: Namespace 'Mocha' has no exported member 'ITestCallbackContext'.
node_modules/mocha-typescript/index.d.ts(20,55): error TS2694: Namespace 'Mocha' has no exported member 'ITestCallbackContext'.
```

**Comment by mbayou** [comment] 2017-04-27 13:28
+1

**Comment by gallayl** [comment] 2017-04-29 17:12
+1

**Comment by pana-cc** [comment] 2017-04-29 18:21
Hi, @mbayou @gallayl could you give v1.1.1 a try?

**Comment by mbayou** [comment] 2017-04-29 19:30
I tried but still doesn't work. However it's not the same error : 

```
Error:(8, 2) TS2345:Argument of type 'typeof AbstractTestController' is not assignable to parameter of type 'SuiteTrait'.
  Type 'typeof AbstractTestController' provides no match for the signature '(this: ISuiteCallbackContext, ctx: ISuiteCallbackContext, ctor: Function): void'
```

See AbstractTestController : 

```
import "reflect-metadata";
import {suite} from "mocha-typescript";
import {AppTestModule} from "./AppTestModule";

/**
 * Abstract controller
 */
@suite
export abstract class AbstractTestController {

    /**
     * Application testing
     */
    private static app: AppTestModule;

    /**
     * Backend
     *
     * @type {string}
     */
    private static backend: string = "http://127.0.0.1:3000";

    /**
     * Method launched before test execution
     */
    public static before(): void {
        AbstractTestController.app = new AppTestModule();
        AbstractTestController.app.bootstrap();
    }

    /**
     * Method launched before test execution
     */
    public static after(): void {
        AbstractTestController.app.rebind();
    }

    /**
     * Get backend
     *
     * @returns {string}
     */
    public static getBackend(): string {
        return this.backend;
    }
}

```

**Comment by gallayl** [comment] 2017-04-29 19:41
Hi @mbayou, I've tried with both 1.1.1 and 1.1.2, worked with no error. Thanks for the quick fix 👍

**Comment by mbayou** [comment] 2017-04-29 19:53
Ok thank you, obviously thats mean my error is caused by my project... Thank for your support ;) I'm trying to fix my project

**Comment by pana-cc** [comment] 2017-04-30 04:17
Base classes without tests doesnt have to be marked with @suite I think. The classes passed to @suite are the leaf classes in the inheritance chain that will get instantiated and their test methods will be called. I am not sure what will happen when @suite is used with abstract class, perhaps I should add some tests to check if the class will be instantiated and add this to the docs.

**Comment by mbayou** [comment] 2017-04-30 12:07
Ok but in this class I wanted to execute the before all and the after all, I was thinking there could not execute if I don't annotate the class... But I've just tried and you're right, it’s definitely not necessary.

**Comment by pana-cc** [comment] 2017-05-20 15:06
I've added several tests that should keep the whole thing working both with and without @types/mocha. I am closing the issue now.

**Closed by pana-cc** 2017-05-20 15:06 UTC
Labels: bug

**Comment by dcharbonnier** [comment] 2018-05-03 12:56
Can we get a clue of what you did to solve this issue ? 'm running on the same issue problem with the last versions.

**Comment by silkentrance** [comment] 2018-05-03 20:00
@dcharbonnier this has long been closed. perhaps you might want to open a new issue and provide a detailed description?

**Comment by dcharbonnier** [comment] 2018-05-04 06:26
yes @pana-cc I think there is a problem when the mocha types does not match, not the first time I run into this issue, I could/should open an other issue but for that I would need to provide a test case and I don't have enough time for that right now.

**Comment by pana-cc** [comment] 2018-05-06 13:34
@silkentrance, @dcharbonnier I think I figured out the problem, but It can't be fixed easily, some vars have become consts and can not longer be redeclared, take a look at #66.

**Comment by cspotcode** [comment] 2018-05-07 02:03
@pana-cc @silkentrance @dcharbonnier

I believe I know the proper solution, based on examples from the community and Microsoft.  Let me know what you think; I'm happy to help make the necessary PR to @types/mocha.

@types/mocha should be declared as a normal dependency, not a peerDependency nor devDependency.  This is the pattern employed by all @types/* packages to enable sharing and extending declarations.  For example, @types/express declares 3 dependencies on other @types/ packages:

https://unpkg.com/@types/express@4.11.1/package.json

I believe those dependencies are generated by [Microsoft/types-publisher](https://github.com/Microsoft/types-publisher) by parsing references in the .d.ts: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/index.d.ts#L14-L17

They're wildcard dependencies so that, if a downstream project installs *any* version of those types, it will be used.  This avoids two versions of a single @types/* package from being installed and conflicting with each other.
